### ISSUE TITLE
Anyone can create a "follows" relationship between any two users

### ISSUE THREAD

**Issue by spalmurray** [CSC207-UofT/course-project-newtapp#26]
Sending a `PUT` request to `/users/follow/{id1}/{id2}` will make user with `id1` follow user with `id2`. 

So, anyone can create a follows relationship between any two users they know the ids of. Since ids are not private information, anyone could easily get the id of any user.

I'm sure you can understand how this could easily be abused...

**Comment by wilgagne** [comment]
Hey, so we still have this issue?  Could we just handle this by changing the API call? or any other insights on how to handle this is welcome

**Comment by spalmurray** [comment]
Solved by your PR!
